### PR TITLE
Fixing implicit bugs

### PR DESCRIPTION
**Pull request by gabrielStanovsky**
* Addressing #36 by ordering the implicit arguments according to the order in which they appeared in the sentence.

* Addressing #25 by removing implicit entities.

* Addressing #37, #38 by better handling of NP modifiers.

### CODE REVIEW

**Comment by gabrielStanovsky** [comment]
@kleinay, can you please try cloning my fork first, and see if this works any better?
If it does, then we can merge, otherwise, let me know what else is going wrong.
That way we can hopefully reduce the number of pull requests :)

**Comment by gabrielStanovsky** [comment]
Evaluation numbers look a little better than before:

```
redicate mentions(F1): 0.262
Entity mentions(F1): 0.448
Predicate coreference: MUC=0.159, B^3=0.601, CEAF_C=0.192, MELA=0.317
Entity coreference: MUC=0.206, B^3=0.660, CEAF_C=0.344, MELA=0.403
```

**Comment by kleinay** [comment]
from a manual testing point of view, It seems better. I'm approving.

**Comment by gabrielStanovsky** [comment]
Thanks, merging.

**Pull request merged**
