### PR TITLE
Integrating PropS proposition extraction

### PR DESCRIPTION
**Pull request by gabrielStanovsky**
@kleinay 
This is a first pull request adding the ability to get the Json objects we discussed.
You can see a usage example in the "main" of the [PropS wrapper](https://github.com/gabrielStanovsky/OKR/blob/props/src/baseline_system/parsers/props_wrapper.py#L304), and also an [example output json](https://github.com/gabrielStanovsky/OKR/blob/props/examples/single_sentence.json).

Please skim these changes, and feel free to ask to change anything that you think can be done better, or ask for clarifications where needed.

Let's discuss these changes here, and decide together when we want to merge them upstream.

Thanks!

### CODE REVIEW

**Review by kleinay — CHANGES_REQUESTED** [review]
I will need another data for the predicate (for the baseline coreference system) - the head lemma and head POS (only head lemma is being used, but I want to respect the API that take both, together with the "Bare predicate").

**Comment by kleinay** [comment]
regarding the "Template" atribute of a predicate: I wonder whether there is a way to facilitate the usage of such template (replacing <A1> signs in a string demands a bit proccessing).

**Comment by kleinay** [comment]
regarding the "Template" atribute of a predicate: I wonder whether there is a way to facilitate the usage of such template (replacing <A1> signs in a string demands a bit proccessing).

**Comment by gabrielStanovsky** [comment]
Changes in c789353729557bda13fe0fb5e31c6467b8c4625b:

* Template - placeholders for predicates and arguments appear with curly braces, so you can replace by using ```format``` with dictionary:
```python
"{A1} forced to land in {A3}".format(**{"A1" : "Plane", "A3" : "Moscow"})
```
* Added the features you requested for the head predicate. These will appear as:
```json
'P1': {"Bare predicate": "was forced",
                       "Head": {"Lemma": "force",
                                "POS": "VBN",
                                "Surface": "forced"},
                       "Template": "{A1} was forced {P2}"}
```
* You can test the single sentence extraction by giving it an input file with raw sentences and an output file where to output a corresponding list of extractions (json format). Try:
```bash
python ./props_wrapper.py --in=../../../examples/raw_sentences --out=../../../examples/raw_sentences.json
```

Additionally, in 22e4849d4d2b4d7294baa69438b3610b71eb5d05 I added list of word indices for both predicates and entities, this usually comes in handy at some point  :)
So now, everything that includes surface words should be a tuple of words and indices:
```
{'Entities': {'A1': ('The Syrian plane', (0, 1, 2)), 'A2': ('Moscow', (8,))},
 'Predicates': {'P1': {'Bare predicate': ('was forced', (3, 4)),
                       'Head': {'Lemma': u'force',
                                'POS': 'VBN',
                                'Surface': ('forced', 4)},
                       'Template': '{A1} was forced {P2}'},
                'P2': {'Bare predicate': ('to land in', (5, 6, 7)),
                       'Head': {'Lemma': 'land',
                                'POS': 'VB',
                                'Surface': ('land', 6)},
                       'Template': '{A1} to land in {A2}'}},
 'Sentence': 'The Syrian plane was forced to land in Moscow .'}
```

**Review by kleinay — APPROVED** [review]

**Comment by kleinay** [comment]
I have another change request for the Predicate data - please add a "Arguments" attribute, containing the symbols in the template. e.g. for predicate with template '{A1} to land in {A2}', add "Arguments":['A1', 'A2'] to its information. should be easy.

**Comment by gabrielStanovsky** [comment]
Done, please review and approve here: https://github.com/vered1986/OKR/pull/5

**Pull request merged**
